---
title: "OPTT Analysis"
author: Oliver Reece
format: pdf
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
#install.packages("tidyquant") #for ticker price data
library("tidyquant") 
#install.packages("lubridate") #for date manipulation
library("lubridate")
#install.packages("tidyverse")
library("tidyverse")
#install.packages("dplyr")
library("dplyr")
#install.packages("zoo") #for time-series analysis
library("zoo")
```

```{r}
#pull OPTT ticker data for all time since going public.
#date format: YYYY-MM-DD

optt <- tq_get("OPTT",
               get = "stock.prices",
               from = "2007-04-25", #went public on NASDAQ April 25th 2007
               to = "2026-06-21") #at time of download, update as needed
```

```{r}
#preview data
head(optt)
```

```{r}
#summary table
summary(optt)
```

```{r}
#tidy datatable

#rename variables to be more 
optt_tidy <- optt |> 
  rename(open_price = open,
         high_price = high,
         low_price = low,
         close_price = close,
         Volume = volume,
         Adjusted = adjusted) |> 

#break date into day, month, year columns
  separate(date, into = c("Year", "Month", "Day"), sep = "-", convert = TRUE) |> 
  
#add month name column
  mutate(month_name = month.name[Month]) |> 
  
#place month name column after month number
  relocate(month_name, .after = Month) |> 

#create new variables
  mutate(
    #intra-day volatility
    idv = (high_price-low_price),
    #previous close price
    prev_close = lag(close_price),
    #absolute maximum upward movement
    max_up = (abs(high_price - prev_close)),
    #absolute maximum downward movement
    max_down = (abs(low_price - prev_close)),
    #true range:
    #use pmax (parallel max) to take max for each day --> eliminates need for if/else + max()
    true_range = pmax(idv, max_up, max_down, na.rm = TRUE),
    #average true range:
    #use rollmean (zoo package) to look at a sliding window
    ATR = rollmean(true_range, k = 14, fill = NA, align = "right")
  )
```

```{r}
#preview tidy data
head(optt_tidy)
```

```{r}
#view summary of tidy data
summary(optt_tidy)
```



















